export const states = [
      { "id": 1, "name": "Acre", "initials": "AC" },
      { "id": 2, "name": "Alagoas", "initials": "AL" },
      { "id": 3, "name": "Amapá", "initials": "AP" },
      { "id": 4, "name": "Amazonas", "initials": "AM" },
      { "id": 5, "name": "Bahia", "initials": "BA" },
      { "id": 6, "name": "Ceará", "initials": "CE" },
      { "id": 7, "name": "Distrito Federal", "initials": "DF" },
      { "id": 8, "name": "Espírito Santo", "initials": "ES" },
      { "id": 9, "name": "Goiás", "initials": "GO" },
      { "id": 10, "name": "Maranhão", "initials": "MA" },
      { "id": 11, "name": "Mato Grosso", "initials": "MT" },
      { "id": 12, "name": "Mato Grosso do Sul", "initials": "MS" },
      { "id": 13, "name": "Minas Gerais", "initials": "MG" },
      { "id": 14, "name": "Pará", "initials": "PA" },
      { "id": 15, "name": "Paraíba", "initials": "PB" },
      { "id": 16, "name": "Paraná", "initials": "PR" },
      { "id": 17, "name": "Pernambuco", "initials": "PE" },
      { "id": 18, "name": "Piauí", "initials": "PI" },
      { "id": 19, "name": "Rio de Janeiro", "initials": "RJ" },
      { "id": 20, "name": "Rio Grande do Norte", "initials": "RN" },
      { "id": 21, "name": "Rio Grande do Sul", "initials": "RS" },
      { "id": 22, "name": "Rondônia", "initials": "RO" },
      { "id": 23, "name": "Roraima", "initials": "RR" },
      { "id": 24, "name": "Santa Catarina", "initials": "SC" },
      { "id": 25, "name": "São Paulo", "initials": "SP" },
      { "id": 26, "name": "Sergipe", "initials": "SE" },
      { "id": 27, "name": "Tocantins", "initials": "TO" }
]

export const paymentMethods = [
  { "id": 1, "name": "Agendamento Eletrônico" },
  { "id": 2, "name": "Averbação" },
  { "id": 3, "name": "Boleto" },
  { "id": 4, "name": "Boleto (Aut)" },
  { "id": 5, "name": "Cartão" },
  { "id": 6, "name": "Cartão (Aut Recorrente)" },
  { "id": 7, "name": "Cartão (Aut)" },
  { "id": 8, "name": "Cartão de Crédito" },
  { "id": 9, "name": "Cartão de Débito" },
  { "id": 10, "name": "Cheque" },
  { "id": 11, "name": "Depósito em conta" },
  { "id": 12, "name": "Desconto em Folha" },
  { "id": 13, "name": "Dinheiro" },
  { "id": 14, "name": "Débito em conta" },
  { "id": 15, "name": "Débito em conta (Aut)" },
  { "id": 16, "name": "Débito no telefone" },
  { "id": 17, "name": "Ocorrências" },
  { "id": 18, "name": "PIX" },
  { "id": 19, "name": "PIX (Aut)" },
  { "id": 20, "name": "Permuta" }
]

export const days = [
  { "day": "1" },
  { "day": "2" },
  { "day": "3" },
  { "day": "4" },
  { "day": "5" },
  { "day": "6" },
  { "day": "7" },
  { "day": "8" },
  { "day": "9" },
  { "day": "10" },
  { "day": "11" },
  { "day": "12" },
  { "day": "13" },
  { "day": "14" },
  { "day": "15" },
  { "day": "16" },
  { "day": "17" },
  { "day": "18" },
  { "day": "19" },
  { "day": "20" },
  { "day": "21" },
  { "day": "22" },
  { "day": "23" },
  { "day": "24" },
  { "day": "25" },
  { "day": "26" },
  { "day": "27" },
  { "day": "28" },
  { "day": "29" },
  { "day": "30" },
  { "day": "31" }
]